server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 43.138.5.79
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
